---
- name: update files
  hosts: master_node
  become: yes 

  tasks: 
    - name: copy file 
      copy: 
        src: ./ 
        dest: ~/jenkins/

    - name: docker build 
      shell: docker build -t wlsthq531jpn/testweb:6.0 ~/jenkins/ 

    - name: docker push 
      shell: docker push wlsthq531jpn/testweb:6.0 

    - name: kubernetes create 
      shell: kubectl apply -f ~/jenkins/nginx.yaml 
